### ISSUE TITLE
Aggregation functions throwing Exception

### ISSUE THREAD

**Issue by mayurchoubey** [tomdz/storm-esper#2]
Hi,

Esper Bolt works well on functions like max or count given in the examples. 
But when I am trying to use functions like Sum or Avg it is throwing following exception:

```
com.espertech.esper.client.EPStatementException: Error starting statement: Implicit conversion from datatype 'Object' to numeric is not allowed for aggregation function 'sum' [select sum(hits) as totalHits from weblogs.win:time_batch(1 sec)]
```

I have gone through the code and found that setupEventTypeProperties() method is putting Object.class for all fields. This could be the reason.

```
 private void setupEventTypeProperties(Fields fields, Map<String, Object> properties)
    {
        int numFields = fields.size();
        for (int idx = 0; idx < numFields; idx++) {
            properties.put(fields.get(idx), Object.class);            
        }
    }
```

Thanks,
Mayur

**Comment by tomdz** [comment]
This requires type hints since Storm does not maintain any type info for the tuples but Esper insists on strongly typed event type declarations before use. See the updated readme and unit tests on how to use them.

**Comment by susangz** [comment]
Hi,

I’m getting the same error (“Implicit conversion from datatype 'Object' to numeric is not allowed”) but with a different situation. Could you please give me any hint to solve it? 

I have a stream of data where the tuples have a known predefined set of fields (e.g. [userdata1,userdata2]) but where one of the fields can be a string or an integer (I don't know the type a priori).

For example:   [userdata1=“A”,userdata2=3] , [userdata1=“B”,userdata2=“xxx”],…

To define EPL statements like:
insert into eventA select \* from stream_default where (userdata1 = "A")
insert into eventB select \* from stream_default where (userdata1 = "B")
insert into alert select a,b from pattern [every (a=eventA) -> b=eventB (a.userdata2=”xxx” and b.userdata2 > 0) where timer:within(var_timeout sec)]

The problem is that I can’t define the fields type from the beginning in the EsperBolt.Builder() with something like:
   .inputs().aliasComponent("spout1A").withFields("userdata1", "userdata2").ofType(String.class,Integer.class).toEventType("Test1A")
because the type of “userdata2” is unknown.

Any idea? Thanks in advance!
    Susana
